Refactor control file
IllumiDesk/illumidesk pull request #524
Opened 2021-03-11 05:43 UTC by jgwerner

- Moves control file creation to grader setup service
- Update setup_course_hook to call grader set service endpoint to register control file

2021-03-11 05:44 UTC, Abhi94N approved these changes
LGTM

2021-03-12 16:07 UTC, Abhi94N requested changes

2021-03-15 14:57 UTC, jgwerner commented on src/grader-service/grader-service/main.py
> +    except Exception as e:
Good catch!

2021-03-15 16:37 UTC, Abhi94N approved these changes
LGTM

2021-03-15 23:56 UTC, merged